# Generated by Django 4.1 on 2022-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnnail',
            field=models.ImageField(default='videos_thumbnail/video_thumbnail_default.png', upload_to='videos_thumbnail/'),
        ),
    ]
