# Generated by Django 4.1 on 2022-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to='users.profile'),
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='users.profile'),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(blank=True, to='users.profile'),
        ),
    ]
