# Generated by Django 4.1 on 2022-08-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0002_video_dislike_video_like_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to='users.profile'),
        ),
    ]
