# Generated by Django 4.1 on 2022-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_tag_video_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='body',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnnail',
            field=models.ImageField(default='images/videos_thumbnail/video_thumbnail_default.png', upload_to='images/videos_thumbnail/'),
        ),
    ]
