# Generated by Django 4.1 on 2022-09-27 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_image_and_more'),
        ('videos', '0004_video_body_alter_video_thumbnnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.profile'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislike', to='users.profile')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to='users.profile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.comments'),
        ),
    ]
