# Generated by Django 4.1 on 2022-10-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_video_comments_comment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='heart',
            field=models.BooleanField(default=False),
        ),
    ]
