# Generated by Django 4.1 on 2022-08-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_thumbnail',
            field=models.ImageField(default='profiles/profile_thumbnail_default.png', upload_to='profiles_thumbnail/'),
        ),
    ]
