# Generated by Django 4.1 on 2022-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_thumbnail',
            field=models.ImageField(default='profiles_thumbnail/profile_thumbnail_default.png', upload_to='profiles_thumbnail/'),
        ),
    ]
