# Generated by Django 4.1 on 2022-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/profiles/user-default.png', upload_to='images/profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_thumbnail',
            field=models.ImageField(default='images/profiles_thumbnail/profile_thumbnail_default.png', upload_to='images/profiles_thumbnail/'),
        ),
    ]
