# Generated by Django 4.1 on 2022-10-18 13:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bell_owner_alter_bell_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/profiles_thumbnail/profile_thumbnail_default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[259, 64], upload_to='images/profiles_thumbnail/'),
        ),
    ]
