# Generated by Django 4.1 on 2022-10-18 13:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_profile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='images/profiles_thumbnail/profile_thumbnail_default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1036, 256], upload_to='images/profiles_thumbnail/'),
        ),
    ]
